# Generated by Django 4.0.1 on 2022-01-10 11:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('Name', models.CharField(max_length=50, primary_key=True, serialize=False, validators=[django.core.validators.MaxLengthValidator(50), django.core.validators.MinLengthValidator(2)])),
                ('Type', models.CharField(max_length=50)),
                ('Generation', models.IntegerField(validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(1)])),
                ('Legendary', models.BooleanField()),
                ('Hp', models.IntegerField(validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(1)])),
                ('Attack', models.IntegerField(validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(1)])),
                ('Defense', models.IntegerField(validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
